upstream {
  # 使用纯数字 IP 替代域名，彻底拒绝因域名解析导致的死循环
  googledns: 'tcp+udp://8.8.8.8:53'
  alidns: 'udp://223.5.5.5:53'
}

routing {
  request {
    # 大陆域名走阿里 DNS 直连解析
    qname(geosite:cn) -> alidns
    
    # 广告域名直接拦截
    qname(geosite:category-ads-all) -> reject
    
    # 海外/常用及兜底域名走 Google DNS 干净解析
    fallback: googledns
  }
}
